# Generated by Django 5.2.8 on 2026-01-17 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hadiya', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('course', 'attendance_date', 'session_year_id')},
        ),
    ]
