# Generated by Django 5.2.8 on 2026-01-17 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hadiya', '0002_alter_attendance_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance_report',
            name='leave_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
