# Generated by Django 5.2.8 on 2026-01-17 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hadiya', '0003_attendance_report_leave_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together=set(),
        ),
    ]
