# Generated by Django 5.2.8 on 2026-01-17 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hadiya', '0004_alter_attendance_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='session_year_id',
        ),
        migrations.RemoveField(
            model_name='student',
            name='session_year_id',
        ),
        migrations.DeleteModel(
            name='Session_year',
        ),
    ]
