# Generated by Django 5.2.8 on 2026-01-18 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hadiya', '0005_remove_attendance_session_year_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='max_ce_marks',
            field=models.FloatField(default=100.0, help_text='Maximum Continuous Evaluation marks'),
        ),
        migrations.AddField(
            model_name='subject',
            name='max_te_marks',
            field=models.FloatField(default=100.0, help_text='Maximum Term End marks'),
        ),
    ]
