# Generated by Django 5.2.8 on 2026-01-25 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hadiya', '0006_subject_max_ce_marks_subject_max_te_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff_leave',
            name='admin_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_leave',
            name='admin_remark',
            field=models.TextField(blank=True, null=True),
        ),
    ]
